<a href="https://colab.research.google.com/github/sooonsyk/ESAA/blob/main/0314_100_Numpy_exercises_1_33.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [38]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [40]:
array4 = np.array([1,2,3,4])
print(array4.size * array4.itemsize)

32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [42]:
array5 = np.zeros(10)
array5[4] = 1
print(array5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [116]:
array8 = np.arange(10, 50)
print(array8[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [49]:
array9 = np.arange(0,9)
array9.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [117]:
array10 = [1,2,0,0,4,0] 
np.nonzero(array10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
np.random.random((3,3,3))

array([[[9.51143707e-01, 1.69740917e-01, 4.16668357e-01],
        [1.61713443e-01, 3.47707087e-01, 7.49520509e-01],
        [3.05074076e-04, 9.62396058e-01, 3.40321983e-03]],

       [[2.29844455e-02, 8.06976987e-01, 4.56239134e-02],
        [2.66612986e-01, 6.73867033e-01, 5.02884878e-01],
        [1.63192118e-01, 1.56997463e-01, 8.32956227e-01]],

       [[1.15880235e-01, 3.71354908e-01, 4.66921740e-01],
        [1.44327640e-01, 6.18048678e-01, 5.15955680e-01],
        [3.51486221e-01, 3.66889163e-01, 7.23650848e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
array13 = np.random.random((10,10))
print(array13)
print(array13.min(), array13.max())

[[0.33363935 0.75454469 0.59425108 0.38832414 0.73655059 0.86874962
  0.33478657 0.30546304 0.76329549 0.36608295]
 [0.2986903  0.68858856 0.79189019 0.72259772 0.53434986 0.8121845
  0.55319244 0.48555716 0.54563205 0.30517298]
 [0.50949703 0.68249753 0.97487048 0.00445741 0.46716897 0.78834045
  0.49698413 0.35367022 0.03589604 0.3380352 ]
 [0.37251291 0.59332145 0.474252   0.27385702 0.79005019 0.34772679
  0.56630675 0.82795457 0.50804998 0.0446927 ]
 [0.55429373 0.49061218 0.17745645 0.25236945 0.40408791 0.6725102
  0.99578559 0.10083689 0.38529685 0.67987944]
 [0.91835992 0.41344193 0.26618772 0.22403762 0.70426636 0.2582257
  0.5319814  0.80473623 0.74398971 0.45347692]
 [0.43866834 0.29689353 0.78299691 0.63896872 0.32850838 0.73203979
  0.22850861 0.61402856 0.36355663 0.7841974 ]
 [0.48143214 0.51380332 0.73927761 0.16352014 0.75010602 0.06573873
  0.94717645 0.80332733 0.71273665 0.94815178]
 [0.64530742 0.79993489 0.67727832 0.25499045 0.41186458 0.50486634
  0.40664233 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [55]:
array14 = np.random.random(30)
print(array14.mean())

0.4664920559768814


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [102]:
array15 = np.zeros((3,3))
np.pad(array15, pad_width=1, mode='constant',
               constant_values=1)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [99]:
array16 = np.random.random((3,3))
np.pad(array16, pad_width=1, mode='constant',
               constant_values=0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.30853886, 0.59607158, 0.2878021 , 0.        ],
       [0.        , 0.75076173, 0.00964039, 0.73607022, 0.        ],
       [0.        , 0.34543269, 0.96163613, 0.14488979, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
nan
False
False
nan
True
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [103]:
np.diag(np.arange(1, 5), k=-1) # k<0: 주 대각선 아래의 대각선에 대입

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [119]:
array19 = np.zeros((8, 8))
array19[::2, 1::2] = 1
array19[1::2, ::2] = 1
print(array19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [120]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [80]:
np.tile([[1,0],[0,1]],[4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [65]:
array22 = np.random.random((5,5))
(array22 - array22.mean())/array22.std()
#array_org = np.random.rand(5, 5)
#eigenvalue, eigenvector = np.linalg.eig(array_org)
#print(eigenvector)

array([[-1.19300333,  1.17904077,  0.66501968,  0.33750858,  1.0807586 ],
       [ 0.41325936, -1.76644988, -0.03417557,  0.56421303, -0.02927582],
       [ 1.15338609,  0.20889271,  0.58214377,  0.01258286,  1.41338145],
       [ 0.78695646,  0.24724354, -0.63148523,  1.26509821, -0.84148976],
       [-1.67242581,  0.66464102, -1.30598044, -1.59266181, -1.50717847]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [68]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(a)
print(b)
print(a@b)

[[0.93662823 0.30895223 0.38549567]
 [0.68644693 0.79178266 0.85270325]
 [0.92295551 0.34183957 0.38712678]
 [0.42669749 0.25627291 0.65285433]
 [0.93423238 0.51590531 0.78487586]]
[[0.57217117 0.44576632]
 [0.87277304 0.37029706]
 [0.27308025 0.34918793]]
[[0.9108281  0.66653186]
 [1.31666812 0.8969434 ]
 [0.93215357 0.67318467]
 [0.64609371 0.51307333]
 [1.19914317 0.88155673]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array25 = np.arange(10)
array25[(array25 > 3) & (array25 < 8)] *= -1
print(array25)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [81]:
print(sum(range(5),-1)) # sum할 대상으로 포함
from numpy import *
print(sum(range(5),-1)) # 축의 의미

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [90]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [91]:
np.array(0) // np.array(0)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [92]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [108]:
array29 = np.random.random(10)
print(array29)
np.around(array29)

[0.34992014 0.35309782 0.69086853 0.09528679 0.04064817 0.40363894
 0.93946191 0.15468154 0.78368452 0.56043142]


array([0., 0., 1., 0., 0., 0., 1., 0., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [106]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a, b))

[4 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [74]:
print(np.sqrt(-1), np.emath.sqrt(-1))

nan 1j


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [124]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2022-03-13 2022-03-14 2022-03-15
