<a href="https://colab.research.google.com/github/sooonsyk/ESAA/blob/main/Week2_HW_100_Numpy_exercises_34_66.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [6]:
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

Numpy 의 날짜/시간 클래스는 datatime64
- 한 클래스로 날짜시간, 날짜, 시간을 모두 정의할 수 있음
- 날짜, 시간 타입은 일반적인 정수, 실수끼리 연산할 때와 달리 단위를 가지고 있는 점 때문에 시간의 차이를 저장하는 별도의 클래스가 있음 -> 이를 timedelta라고 함 
- 날짜, 시간은 특정 시점의 시각을 표시하는 용도이고(2021년 3월 16일), 타임델타는 기간 또는 시간 차이를 표시하는 용도(5일)

출처: https://ellun.tistory.com/320 [Ellun's Library]
 타임델타 클래스는 timedelta64

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [78]:
A = np.arange(5) * 1.0  #divide한 결과 값을 저장하려면 A가 float이어야 함
B = np.ones(5)
print(A, B)
np.add(A,B,out=B)   # A*B를 B에 저장
np.negative(A,out=A)  # -A를 A에 저장
np.divide(A,2,out=A)  # A/2를 A에 저장 즉 -A/2
np.multiply(A,B)   #(A+B)가 B에 (-A/2)가 A에 저장되어있으므로  

[0. 1. 2. 3. 4.] [1. 1. 1. 1. 1.]


array([ -0.,  -1.,  -3.,  -6., -10.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [11]:
array36 = np.random.uniform(0,10,10) #uniform 분포 0~10을 넘지 않는 수 중 10개 
print(array36)

[9.34350262 2.98750517 5.41255198 8.16708731 1.48165041 0.1515026
 3.68037973 3.89568283 1.24706361 9.97076424]


In [20]:
print(array36 // 1)  #1로 나눈 몫
print(array36 - array36 % 1) # 원래 값에서 1로 나눈 나머지 뺴줌
print(np.floor(array36)) #버림
print(array36.astype('int'))  #정수로 타입 변환

[9. 2. 5. 8. 1. 0. 3. 3. 1. 9.]
[9. 2. 5. 8. 1. 0. 3. 3. 1. 9.]
[9. 2. 5. 8. 1. 0. 3. 3. 1. 9.]
[9 2 5 8 1 0 3 3 1 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [23]:
array37 = np.zeros((5,5))
array37 += np.arange(0,5)
print(array37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [46]:
np.random.randint(0,100,10)

array([12, 30, 24, 16, 29, 58, 74, 50, 89, 76])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [28]:
np.linspace(0,1,11, endpoint = False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

linspace() : 일정 간격으로 array 생성
- start 부터 end까지 일정 간격으로 array를 생성하고 endpoint로 end 포함 여부 설정 가능

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
array40 = np.random.random(10)
print(array40)
print(sorted(array40))

[0.38944106 0.04853889 0.8551897  0.58130558 0.33362214 0.04580377
 0.40261696 0.2122648  0.37941979 0.32336734]
[0.045803768976765635, 0.048538885258757936, 0.2122647982096023, 0.3233673397601864, 0.33362214376913846, 0.3794197938642736, 0.3894410641761161, 0.4026169640665175, 0.5813055800279638, 0.8551897037994448]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [2]:
%%time
array41 = np.arange(10)
np.sum(array41)

CPU times: user 1.26 ms, sys: 0 ns, total: 1.26 ms
Wall time: 5.03 ms


In [4]:
%%time
array41 = np.arange(10)
np.add.reduce(array41)

CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.44 ms


- reduce() : 해당연산을 배열 요소에 반복 적용해줌
- %%time : jupyter에서 한 cell의 실행시간을 출력해줌


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [36]:
A = np.random.random(10)
B = np.random.random(10)
print(A)
print(B)
np.array_equal(A,B)

[0.11966142 0.80353596 0.92580991 0.18535398 0.52513992 0.26321979
 0.72321151 0.02451226 0.46818845 0.75377351]
[0.08106608 0.08108216 0.66812283 0.23242862 0.42198944 0.32877393
 0.20852977 0.01346885 0.0716275  0.50209232]


False

np.array_equal() : 2개의 배열이 동일한지 비교해줌
- nan이 포함된 경우 다르다고 나옴




#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
array43 = np.random.random(10)
array43.flags.writeable = False
print(array43)
array43[0] = 0

[0.31875195 0.45596623 0.96712236 0.44230697 0.251311   0.28388834
 0.11273786 0.69335796 0.08957091 0.94914145]


ValueError: ignored

ndarray.flags : Information about the memory layout of the array.
- WRITEABLE (W) : Setting this to False locks the data, making it read-only. 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [8]:
array44 = np.random.random((10,2))
print(array44)
X = array44[:,0]
Y = array44[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X) 
print(R, T)

[[0.53835993 0.54999601]
 [0.55557946 0.3503319 ]
 [0.06356413 0.05269164]
 [0.93279089 0.54438872]
 [0.23737589 0.49820893]
 [0.21540938 0.89234791]
 [0.37515786 0.59376965]
 [0.54910502 0.74178275]
 [0.42999432 0.68786106]
 [0.51387113 0.11077921]]
[0.76962785 0.65681122 0.08256396 1.08002681 0.55186905 0.9179793
 0.70235733 0.92290734 0.81120155 0.5256763 ] [0.79608918 0.56259489 0.69214721 0.52828295 1.12615864 1.33393162
 1.00730497 0.93356418 1.01211217 0.21232837]


- numpy.arctan(x1, x2) : arc tangent of x1/x2 : 출력 범위가 [-pi/2, pi/2], 180도 이상 차이나는 각의 arctan 값은 구분이 안됨(ex: arctan(0), arctan(180) 은 같음).

- numpy.arctan2(x1, x2) : arc tangent of x1/x2, 출력 범위가 [-pi, pi], C언어 atan2 함수와 같음.


출처: https://belitino.tistory.com/264 [belitino]

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:
array45 = np.random.random(10)
print(array45)
array45[array45.argmax()] = 0
print(array45)

[0.82781278 0.71544508 0.98088615 0.66886972 0.14437605 0.02759876
 0.97395218 0.71896052 0.74694878 0.90940589]
[0.82781278 0.71544508 0.         0.66886972 0.14437605 0.02759876
 0.97395218 0.71896052 0.74694878 0.90940589]


ndarray.argmax() : array 속 최댓값의 index를 반환하는 함수

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [81]:
array46_struct = np.dtype([('x','float'),('y','float')])
np.zeros((5,5),array46_struct)

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [49]:
X = np.random.random(10)
Y = np.random.random(10)
C = 1/np.subtract.outer(X,Y)
print(C)

[[  -26.7892124     -2.29451569    -2.9080843     -1.29879299
     -5.10317445   -10.82132304    -2.25123713   -18.04423657
     -2.27519507    -1.64106973]
 [    1.81130837     6.51068166     4.07254705    -5.53924327
      2.54156018     2.01205047     6.88632386     1.87267247
      6.67143388   -50.14275637]
 [    3.27287873   -10.75824715 -1000.8876079     -2.34150489
      6.8067304      3.9926578     -9.86871324     3.47885965
    -10.34630329    -3.75250358]
 [    7.76384555    -3.70794435    -5.6262469     -1.65613631
    -33.52796169    13.56475411    -3.59622198     9.03250566
     -3.65774958    -2.25617506]
 [    1.30728132     2.72886342     2.18147344    30.93187649
      1.64929875     1.40871934     2.79271458     1.33894728
      2.75670432     5.18359992]
 [    4.6713852     -5.42228498   -10.81417048    -1.92846209
     18.03710676     6.28979942    -5.1866552      5.10260402
     -5.31561381    -2.79360118]
 [    5.20008923    -4.84992       -8.75379749    -1.85077

numpy.ufunc.outer() : Apply the ufunc op to all pairs (a, b) with a in A and b in B.

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [10]:
print(np.iinfo(np.int8).min, np.iinfo(np.int8).max )
print(np.iinfo(np.int32).min, np.iinfo(np.int32).max )
print(np.iinfo(np.int64).min, np.iinfo(np.int64).max )
print(np.finfo(np.float32).min, np.finfo(np.float32).max )

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38


- iinfo와 finfo는 각각 int와 float의 표현가능한 수의 한계를 반환

#### 49. How to print all the values of an array? (★★☆)

In [13]:
np.set_printoptions(threshold=np.inf)
#한 라인의 너비를 무한대로 설정

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [13]:
array50 = np.random.randint(0,100,30)
num = np.random.randint(0,100,1)
print(array50, num)
np.abs(array50 - num).argmin()
#차의 절댓값이 가장 작은 index 반환

[23 77 51 49 63 74 99 11 55 41 32 22 52 43 21 56 74 23  0 72 63  2 49 74
 82 10 20 20 42 52] [64]


4

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [59]:
array51_struct = np.dtype([('xy','f',2),('rgb','f',3)])
np.zeros(10, array51_struct)

array([([0., 0.], [0., 0., 0.]), ([0., 0.], [0., 0., 0.]),
       ([0., 0.], [0., 0., 0.]), ([0., 0.], [0., 0., 0.]),
       ([0., 0.], [0., 0., 0.]), ([0., 0.], [0., 0., 0.]),
       ([0., 0.], [0., 0., 0.]), ([0., 0.], [0., 0., 0.]),
       ([0., 0.], [0., 0., 0.]), ([0., 0.], [0., 0., 0.])],
      dtype=[('xy', '<f4', (2,)), ('rgb', '<f4', (3,))])

dtype를 지정해서 structured array 만듦
- 각각 x,y를 나타내는 float 2개의 tuple과 각각 r,g,b를 나타내는 float 3개의 tuple이 한 쌍이 되어 하나의 element가 됨

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [6]:
array52 = np.random.random((10,2))
print(array52)
X, Y = np.atleast_2d(array52[:,0], array52[:,1])
print(X, Y)
np.sqrt((X-X.T)**2 + (Y-Y.T)**2)


[[0.36914016 0.09274678]
 [0.8799969  0.71298482]
 [0.2402256  0.66018225]
 [0.80529019 0.25840883]
 [0.30917779 0.66617826]
 [0.52935304 0.28029943]
 [0.05907566 0.54924312]
 [0.38816171 0.30600472]
 [0.82365256 0.6065951 ]
 [0.77633476 0.90629257]]
[[0.36914016 0.8799969  0.2402256  0.80529019 0.30917779 0.52935304
  0.05907566 0.38816171 0.82365256 0.77633476]] [[0.09274678 0.71298482 0.66018225 0.25840883 0.66617826 0.28029943
  0.54924312 0.30600472 0.6065951  0.90629257]]


array([[0.        , 0.80353583, 0.58189516, 0.46655199, 0.57655802,
        0.24666609, 0.55184138, 0.21410457, 0.68601867, 0.90976051],
       [0.80353583, 0.        , 0.6419466 , 0.46067388, 0.57273494,
        0.55692707, 0.83709201, 0.63838441, 0.12038877, 0.21934841],
       [0.58189516, 0.6419466 , 0.        , 0.69333965, 0.0692124 ,
        0.47739463, 0.21242126, 0.38383176, 0.58588275, 0.58990111],
       [0.46655199, 0.46067388, 0.69333965, 0.        , 0.64218644,
        0.2768041 , 0.80088746, 0.41983513, 0.34867013, 0.64853046],
       [0.57655802, 0.57273494, 0.0692124 , 0.64218644, 0.        ,
        0.44427426, 0.27608858, 0.36873221, 0.51791355, 0.52525281],
       [0.24666609, 0.55692707, 0.47739463, 0.2768041 , 0.44427426,
        0.        , 0.54174859, 0.14351221, 0.43940992, 0.67295422],
       [0.55184138, 0.83709201, 0.21242126, 0.80088746, 0.27608858,
        0.54174859, 0.        , 0.40922189, 0.76672491, 0.80121466],
       [0.21410457, 0.63838441, 0.3838317

numpy.atleast_2d() : View inputs as arrays with at least two dimensions.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [68]:
array53 = np.arange(10, dtype = np.float32)
print(array53)
array53.astype(np.int32)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [8]:
from io import StringIO

string = StringIO("""1, 2, 3, 4, 5
                     6,  ,  , 7, 8\n
                     ,  , 9,10,11\n""")
np.genfromtxt(string, delimiter=",", dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

- StringIO 는 파일처럼 취급되는 객체를 만들지만 실제 파일은 아니고 보여주기 위한 코드임
- numpy.genfromtxt() : 텍스트 파일을 numpy array 형식으로 바꾸어줌
 - 불러올 파일의 주소를 먼저 입력하고, dtype은 파일에서 불러온 행렬을 어떤 데이터 타입으로 출력할질 정하는 것이고, delimiter=' '는 불러오는 파일에 있는 데이터들을 띄어쓰기를 기준으로 행렬의 성분으로 인식하겠다는 겁니다.
[출처] Python_Numpy_행렬입출력 genfromtxt|작성자 캘리집

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [15]:
array55 = np.arange(9).reshape(3,3)
print(array55)
for index, x in np.ndenumerate(array55):
  print(index, x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


numpy.ndenumerate(arr): Multidimensional index iterator.
- Return an iterator yielding pairs of array coordinates and values.

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [9]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
np.exp(-((D-mu)**2 / 2*sigma**2))

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [14]:
array57 = np.zeros((5,5))
p = 3
np.put(array57, np.random.choice(range(5*5),p,replace=False),1)
# array57의 5*5개의 element 중 랜덤으로 p개 뽑아서 1로 값을 바꿔줌
print(array57)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


- numpy.put(a, ind, v, mode='raise') : Replaces specified elements of an array with given values
 - 사용할 array, 넣을 곳의 index, 넣을 값
 - mode는 optional

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [20]:
array58 = np.random.random((5,10))
array58 - array58.mean(axis = 1, keepdims = True)
# axis = 1로 row 선택, keepdims로 차원 유지

array([[ 0.26795887,  0.1881162 , -0.12151188, -0.34633434, -0.27503042,
         0.51968841, -0.04989922,  0.35077522, -0.44096525, -0.09279758],
       [ 0.21663628, -0.19792596, -0.42484308, -0.01833404,  0.20986014,
         0.06221272,  0.20861427,  0.07632005, -0.20733032,  0.07478994],
       [ 0.39917077,  0.45833499, -0.49998033,  0.31391641, -0.13512285,
         0.15285982,  0.07822805, -0.31265976, -0.41561142, -0.03913567],
       [ 0.42669771,  0.41585941, -0.4240254 ,  0.42956801, -0.13066035,
        -0.2366596 ,  0.04620658,  0.06103151, -0.1655577 , -0.42246018],
       [-0.4838162 ,  0.30884218,  0.18373749, -0.31837191,  0.21665467,
         0.23186   , -0.15739039,  0.02182019,  0.28897481, -0.29231083]])

#### 59. How to sort an array by the nth column? (★★☆)

In [21]:
array59 = np.random.randint(0,10,(3,3))
print(array59)
print(array59[array59[:,0].argsort()])

[[9 9 0]
 [5 1 2]
 [2 8 3]]
[[2 8 3]
 [5 1 2]
 [9 9 0]]


numpy.argsort(a, axis=- 1, kind=None, order=None)
: Returns the indices that would sort an array.

- Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [29]:
array60 = np.array([0,1,2,0,3,4,0,5,6]).reshape(3,3)
print(array60)
print(~array60.any(axis=0))
print((~array60.any(axis=0)).any())

[[0 1 2]
 [0 3 4]
 [0 5 6]]
[ True False False]
True


numpy.any() : 인자에 전해진 배열에 하나라도 0이 아닌 수가 있다면 True 반환

- ~array60.any(axis=0) : col이 nonzero인 수를  하나라도 가지면 False가 나옴, null로만 이루어진 경우 True 반환
-(~array60.any(axis=0)).any() : 하나라도 null로만 이루어진 col이 있는 경우 True 반환

#### 61. Find the nearest value from a given value in an array (★★☆)

In [23]:
#50번과 유사
array61 = np.random.random(10)
num = np.random.random(1)
print(array61, num)
array61[np.abs(array61 - num).argmin()]

[0.63027203 0.50759677 0.15774539 0.97932559 0.60463256 0.70847121
 0.9609397  0.39912353 0.35618325 0.56113047] [0.21758287]


0.1577453902649817

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [22]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x + y
print(it.operands[2]) #z출력

[[0 1 2]
 [1 2 3]
 [2 3 4]]


- numpy.nditer() : for문을 사용하지 않고 다차원 배열을 순회하게 하는 함수




#### 63. Create an array class that has a name attribute (★★☆)

In [44]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', 'no name')
        
array63 = NameArray(np.arange(10), 'array63')
print(array63.name)

array63


In [49]:
help(np.__new__)

Help on built-in function __new__:

__new__(*args, **kwargs) method of builtins.type instance
    Create and return a new object.  See help(type) for accurate signature.



- __new__ is a standard Python method, and, if present, is called before __init__ when we create a class instance. 
- __array_finalize__ is the mechanism that numpy provides to allow subclasses to handle the various ways that new instances get created.

출처 : https://numpy.org/doc/1.14/user/basics.subclassing.html

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [33]:
A = np.zeros(5)
B = np.random.randint(0,5,10)
np.add.at(A,B,1) #A[B]에 +1
print(A,B)

[0. 5. 1. 1. 3.] [1 2 1 4 1 1 4 3 1 4]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [26]:
X = np.random.randint(1,10,5)
I = np.random.randint(1,10,5)
print(A, B)
F = np.bincount(I,X)  #I의 index에 X를 weight로 빈도수 계산
print(F)

[5 6 8 6 8] [3 9 6 9 2]


array([ 0.,  0.,  8.,  5.,  0.,  0.,  8.,  0.,  0., 12.])

- numpy.bincount() : 빈도수 계산

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [46]:
I = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 + I[...,2]
print(len(np.unique(F)))

8
