<a href="https://colab.research.google.com/github/sooonsyk/ESAA/blob/main/Week2_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**파이썬 머신러닝 완벽 가이드 p. 39 ~ 86**

##데이터 핸들링 - 판다스
###판다스
- 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리할 수 있는 기능 제공
- 파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터뿐만 아니라 CSV등의 파일을 쉽게 Dataframe으로 변경해 데이터의 가공/분석을 편리하게 수행할 수 있게 만들어줌
- Dataframe : 판다스의 핵심 객체, 여러개의 행과 열로 이루어진 2차원 데이터를 담는 데이터 구조체
  - Index : 개별 데이터를 고유하게 식별하는 key
  - Series : 칼럼이 하나뿐인 데이터 구조체
  - Series와 Dataframe 모두 Index를 key 값으로 가짐
  - Dataframe은 여러개의 Series로 이루어졌다고 할 수 있음

###판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

```
import pandas as pd
```
- 판다스는 다양한 포맷으로 된 파일을 DataFrame으로 로딩할 수 있는 편리한 API 제공
  - read_csv() : CSV(칼럼을 ','으로 구분한 파일 포맷) 파일 포맷 변환을 위한 API
  - read_table() : 필드 구분 문자(delimeter)가 '\t'
  - read_fwf() : fixed width 즉 고정 길이 기반의 칼럼 포맷을 위한 API
  - 구분문자는 sep 옵션을 통해 설정 가능
  - 로드하려는 데이터 파일의 경로를 포함하는 파일명을 입력하면 파이썬 실행 파일이 있는 디렉터리와 동일한 디렉터리에 있는 파일명을 로딩함





In [ ]:
import pandas as pd

In [ ]:
titanic_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')
print('titanic 변수 type : ', type(titanic_df))
titanic_df

titanic 변수 type :  <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

- pd.read_csv() : 호출 시 파일명 인자로 들어온 파일을 로딩해 DataFrame 객체로 반환
  - 별다른 파라미터 지정이 없으면 파일의 맨 처음 로우를 칼럼명으로 인지하고 칼럼으로 변환함
  - 파일에 기재돼 잇지 않는 데이터값이 로우 순으로 0,1,2,3....과 같이 순차적으로 표시돼 있음 - 판다스의 index 값
    - 모든 DataFrame내의 데이터는 생성되는 순간 고유의 Index값을 가짐

- DataFrame.head() : DataFrame의 맨 앞에 잇는 N개의 로우 반환, default 5개

In [ ]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

- DataFrame.shape : DataFrame의 행과 열의 튜플로 반환

In [ ]:
print('DataFrame 크기 : ', titanic_df.shape)

DataFrame 크기 :  (891, 12)


- DataFrame.info() : 총 데이터 건수와 데이터 타입, Null 건 수 알 수 있음

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- DataFrame.describe() : 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값을 나타냄, 오직 숫자형(int,float 등) 칼럼의 분포도만 조사하며 자동으로 object 타입의 칼럼은 출력에서 제외시킴
  - count : not null인 데이터 건수
  - mean : 전체 데이터 값의 평균
  - std : 표준편차
  - min : 최솟값
  - max : 최댓값
  - 해당 숫자 칼럼이 숫자형 카테고리 칼럼(특정 번주에 속하는 값을 코드화한 칼럼)인지를 판단할 수 있게 도와줌

In [ ]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

- DataFrame의 [ ] 연산자 내부에 칼럼며을 입력하면 Series 형태로 특정 칼럼 데이터 세트가 반환됨
- Series : Index와 단 하나의 칼럼으로 구성된 데이터 세트
- value_counts() : 이렇게 반환된 Series 객체에 호출하면 해당 칼럼값의 유형과 건수를 확인할 수 있음, 지정된 칼럼의 데이터값 건수 반환
  - 많은 건수 순서로 정렬되어 값을 반환
  - DataFrame은 가지지 않음
  - 반환하는 값 역시 Series 객체
- 인덱스는 단순히 순차 값과 같은 의미 없는 식별자만 할당하는 것이 아니라 고유성이 보장된다면 의미 있는 데이터값 할당도 가능
  - value_counts()는 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용할 수 있음
  - 인덱스는 후에 변경 가능, 숫자형뿐만 아니라 문자열도 가능, 단, 모든 인덱스는 고유성이 보장돼야 함

In [ ]:
titanic_pclass = titanic_df['Pclass']
type(titanic_pclass)

pandas.core.series.Series

In [ ]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [ ]:
type(titanic_pclass.value_counts())

pandas.core.series.Series

###DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
- 기본적으로 DataFrame은 파이썬의 리스트, 딕셔너리, 그리고 넘파이 ndarray등 다양한 데이터로부터 생성될 수 있음, 또 반대로 변환될 수도 있음
####**넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기**
- DataFrame은 리스트와 넘파이 ndarray와 다르게 칼럼명을 가지므로 리스트와 넘파이 ndarray보다 상대적으로 편하게 데이터 핸들링 가능
  - 일반적으로 DataFrame으로 변환 시 칼럼명을 지정해줌( 지정하지 않으면 자동으로 할당)
- 판다스 DataFrame 객체의 생성 인자 data는 리스트나 딕셔너리 또는 넘파이 ndarray를 입력 받고, 생성 인자 colums는 칼럼명 리스트를 입력 받아 DataFrame 생성
  - DataFrame은 기본적으로 행과 열을 가지는 2차원 데이터 이므로 2차원 이하의 데이터들만 DataFrame으로 변환될 수 있음

In [ ]:
#1차원 형태의 list, 넘파이 ndarray 변환
import numpy as np

col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape : ', array1.shape)

#리스트 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame : \n', df_list1)

#넘파이 ndarray 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame :\n', df_array1)

array1 shape :  (3,)
1차원 리스트로 만든 DataFrame : 
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame :
    col1
0     1
1     2
2     3


In [ ]:
#2차원 형태(2,3)의 데이터 변환

col_name2 = ['col1','col2','col3'] # 칼럼 3개니까 칼럼명 3개 필요
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print('array2 shape : ', array2.shape)
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape :  (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [ ]:
#딕셔너리 변환 : 일반적으로 key를 칼럼명으로 value를 키에 해당하는 칼럼 데이터로

dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


####**DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기**

In [ ]:
#DataFrame을 ndarray로 변환 - DataFrame 객체의 values를 이용해 쉽게 가능

array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape: ', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape:  (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [ ]:
#DataFrame을 리스트로 변환 - values로 얻은 ndarray에 tolist() 호출
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
list3

df_dict.values.tolist() 타입: <class 'list'>


[[1, 2, 3], [11, 22, 33]]

In [ ]:
#DataFrame을 딕셔너리로 변환 - DataFrame 객체의 to_dict() 메서드 호출
dict3 = df_dict.to_dict('list') # 인자로 'list'를 입력하면 딕셔너리의 값이 리스트형으로 반환됨
print('\n df_dict.to_dict() 타입 : ', type(dict3))
dict3


 df_dict.to_dict() 타입 :  <class 'dict'>


{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

####**DataFrame의 칼럼 데이터 세트 생성과 수정**
- DataFrame의 칼럼 데이터 세트 생성과 수정 역시 [ ] 연산자를 이용해 쉽게 할 수 있음


In [ ]:
titanic_df['Age_0'] = 0  #새로운 칼럼 Age_0 추가하고 일괄적으로 0 할당
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [ ]:
#기존 칼럼 Series의 데이터를 이용해 새로운 칼럼 Series 만듦
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [ ]:
#기존 칼럼 업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_No  
0          2  
1          2  
2          1

####**DataFrame 데이터 삭제**
- drop() : labels에 원하는 칼럼명을 입력하고 axis=1을 입력하면 지정된 칼럼을 드롭
  - axis 값에 따라서 특정 칼럼 또는 특정 행 드롭 - axis0 ↓ : 로우 방향 축, axis1 → : 칼럼 방향 축
  - Inplace : 디폴트가 False로 자기 자신의 DataFrame의 데이터는 삭제하지 않고 삭제된 결과 Df를 반환, True로 설정하면 반환값이 None이 되므로 반환 값을 다시 자신의 DataFrame객체로 할당하면 안 됨
  - 여러 개의 칼럼을 삭제하고 싶르면 리스트 형태로 삭제하고자 하는 칼럼 명을 입력해 label 파라미터로 입력

In [ ]:
#Age_0 칼럼 삭제
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1

In [ ]:
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'], axis=1, inplace=True)
print('inplace=True 로 drop 후 반환된 값: ', drop_result)
titanic_df.head(3)

inplace=True 로 drop 후 반환된 값:  None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

####**Index 객체**
- DataFrame, Series의 레코드를 고유하게 식별하는 객체
- DataFrame.index, Series.index 속성으로 통해 Index 객체만 추출 가능
- Series 객체는 Index 객체를 포함하지만 Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외됨, Index는 오직 식별용
- reset_index() : 새롭게 인덱스를 연속 숫자 형으로 할당하고 기존 인덱스는 'index'라는 새로운 칼럼 명으로 추가함
  - 인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용
  - Series에 reset_index()를 적용하면 Series가 아닌 DataFrame이 반환됨 - 기존 인덱스가 칼럼으로 추가돼 칼럼이 2개가 되므로
  - drop=True로 설정하면 기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제되고 Series로 유지됨

In [37]:
#원본 파일 다시 로딩
titanic_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')

#index 객체 추출
indexes = titanic_df.index
print('Index 객체 : ',indexes)
#index 객체를 실제 값 array로 변환 - 넘파이 1차원 ndarray로 볼 수 있음
print('Index 객체 array 값:\n', indexes.values)

Index 객체 :  RangeIndex(start=0, stop=891, step=1)
Index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 22

In [39]:
# ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [40]:
#한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경할 수 없음
indexes[0] = 5

TypeError: ignored

In [42]:
series_fair = titanic_df['Fare']
print('Fair Series max 값 : ', series_fair.max())
print('Fair Series sum 값 : ', series_fair.sum())
print('sum() Fair Series :', sum(series_fair))
print('Fair Series + 3:\n', (series_fair+3).head(3))

Fair Series max 값 :  512.3292
Fair Series sum 값 :  28693.9493
sum() Fair Series : 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [41]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [43]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)

print('### after reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입 : ', type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### after reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입 :  <class 'pandas.core.frame.DataFrame'>
