<a href="https://colab.research.google.com/github/sooonsyk/ESAA/blob/main/Week1_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. 파이썬 기반의 머신러닝과 생태계 이해**
##1) 머신러닝의 개념
: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

: 복잡한 조건/규칙들이 다양한 형태로 결합하고 시시각각 변하면서 도저히 소프트웨어 코드로 로직을 구성하여 이들을 관통하는 일정한 패턴을 찾기 어려운 경우에 유용

: 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출

####분류
- 지도학습 supervised learning
  - 분류
  - 회귀
  - 추천 시스템
  - 시각/음성 감지/인지
  - 텍스트 분석, NLP
- 비지도학습 un-supervised learning
  - 클러스터링
  - 차원 축소
  - 강화학습

####데이터 전쟁
: 머신러닝의 가장 큰 단점은 데이터에 매우 의존적이라는 것

: 최적의 머신러닝 알고리즘과 모델 파라미터를 구축하는 능력도 중요하지만 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동하라 수 있도록 준비하는 능력이 더 중요할 수 있음

####파이썬과 R기반의 머신러닝 비교
- R : 통계 전용 프로그램 언어
- 파이썬 : 다양한 영역에서 사용되는 개발 전문 프로그램 언어, 뛰어난 개발 생산성, 오픈 소스, 많은 라이브러리로 높은 생산성, 확장성, 유연성, 호환성
- R < 파이썬

##2) 파이썬 머신러닝 생태계를 구성하는 주요 패키지
- 머신러닝 패키지 : 사이킷런 Scikit-Learn, 텐서플로, 케라스
- 행렬/선형대수/통계 패키지 : 넘파이 Numppy, 사이파이 Scipy
- 데이터 핸들링 : 판다스, 맷플롯립 Matplotlib
- 시각화 : 맷플롯립, 시본 Seaborn

##3)넘파이
: NumPy = Numerical Python, 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

\- 루프를 사용하지 않고 대량 데이터의 배열 연산을 간으하게 함 --> 빠른 배열 연산 속도
\- 파이썬 언어 자체가 가지는 수행 성능의 제약이 있으므로 수행 성능이 매우 중요한 부분은 C/C++기반의 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 쉽게 통합할 수 있음

####넘파이 ndarray 개요
\- 넘파이의 기반 데이터 타입 : ndarray
\- ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음

In [8]:
import numpy as np
#as 사용해서 약어로 모듈을 표현해주는 게 관례

array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array2 = np.array([[1,2,3],
                   2,3,4])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

print('array1 : {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (4,)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
array1 : 1차원, array2: 1차원, array3:  2차원


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if __name__ == '__main__':


- array() : 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능 수행
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray배열의 차원까지 알 수 있음
- array1 과 array3 은 동일한 데이터 건수를 가지고 있지만, array1은 명확하게 1차원임을 (3,)로 표현한 것이고 array3은 명확하게 로우와 칼럼으로 이뤄진 2차원 데이털임을 (1,3)으로 표현한 것

####ndarray의 데이터 타입
- ndarray내의 데이터값은 숫자 값(int, unsigned int, float, complex), 문자열 값, 불 값 등이 모두 가능
- ndarray내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능 <-> list
  - 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용
- ndarray내의 데이터 타입은 dtype 속성으로 확인할 수 있음

In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# 숫자형 값이 모두 유니코드 문자열 값으로 변환됨

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# int가 모두 float64로 변환됨

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- ndarray 내 데이터값의 변경도 astype()로 가능
  - astype()에 인자로 원하는 타입을 문자열로 지정
  - 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용됨, 메모리를 더 절약해야할 때 보통 이용됨

In [15]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') 
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


####ndarray를 편리하게 생성하기 - arange, zeros, ones
: 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있음 - arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있음
- 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용



- arange() : 함수 이름에서 알 수 있듯 파이썬 표준 함수인 range()와 유사한 기능, array를  range()로 표현하는 것으로 쉽게 생각
  - 0부터 함수 인자 값-1 까지의 값을 순차적으로 ndarray의 데이터 값으로 변환
  - default 함수 인자는 stop값
  - start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있음
  

In [19]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- zeros() : 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환함
- ones() : 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환
  - 함수 인자로 dtype를 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [20]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


####ndarray의 차원과 크기를 변경하는 reshape()
- reshape() : ndarray를 특정 차원 및 크기로 변환, 원하는 크기를 함수인자로 부여
  - 지정된 사이즈로 변경이 불가능하면 오류 발생
  - 인자로 -1을 적용하는 경우에 유용하게 사용 - 원래 ndarray와 호환되는 새로운 shape로 변환 - 마찬가지로 호환될 수 없는 형태는 변환할 수 없음

In [21]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)  #5개의 col에 맞는 row 개수로 맞춰줌
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)  #5개의 row에 맞는 col 개수로 맞춰줌
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


- -1 인자는 reshape(-1,1)과 같은 형태로 자주 사용 - 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 row를 가지되 반드시 한 개의 col을 가진 ndarray로 변환됨을 보장

In [27]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())  # tolist() : ndarray를 리스트형으로 변환

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) 
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


####넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨
2. 슬라이싱 slicing : 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식, ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환
3. 팬시 인덱싱 fancy indexing : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
4. 불린 인덱싱 boolean indexing : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

- 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입

**-단일 값 추출**


In [28]:
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

value = array1[2]  #0부터 시작하므로 3번째 위치의 값, 마이너스 기호 사용하면 맨 뒤에서부터 데이터 추출
print('value :', value)
print(type(value)) #array1[2]는 더이상 ndarray 타입이 아니고 ndarray내의 데이터값 의미

array1: [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int64'>


In [29]:
array1[0] = 9
array1[8] = 0
print('array1', array1)  #단일 인덱스를 이용해 ndarray내의 데이터값도 간단히 수정 가능

array1 [9 2 3 4 5 6 7 8 0]


In [32]:
#다차원 ndarray에서 단일 값 추출
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=1, col=1) index 가리키는 값:', array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=1, col=1) index 가리키는 값: 5


- axis 0 : row 방향의 축
- axis 1 : col 방향의 축
  - **row 와 col은 ndarray에서는 사용되지 않는 표현! axis 0, axis 1 이 올바른 표현**

**-슬라이싱**
- ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인댁스를 생략하면 자동으로 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨처음/맨 마지막 인덱스로 간주

In [33]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [37]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [38]:
#다차원 ndarray에서 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])  # 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [39]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**-팬시 인덱싱**

In [41]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


**-불린 인덱싱**

In [43]:
array1d = np.arange(1,10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 : ', array3)

array1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [48]:
array1d > 5  # True 위치에 해당하는 값만

array([False, False, False, False, False,  True,  True,  True,  True])

In [47]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ', array3)  #결과 동일

불린 인덱스로 필터링 결과 :  [6 7 8 9]


####행렬의 정렬 - sort()와 argsort()
**-행렬 정렬**
- np.sort() : 넘파이에서 sort()를 호출하는 방식, 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식, 원 행렬 자체를 정렬한 형태로 변환, 반환 값 None
- 모두 기본적으로 오름차순 정렬, 내림차순 정렬하기 위해서는 [::-1] 적용
- 다차원 행렬일 경우 axis 축 값 설정을 통해 row 방향, 또는 col 방향으로 정렬 수행 가능

In [49]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('ndarray.sort() 호출 후 반환된 행렬 :', sort_array2)
print('ndarray.sort() 호출 후 원본 행렬 : ', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
ndarray.sort() 호출 후 반환된 행렬 : None
ndarray.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [50]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [51]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('col 방향으로 정렬 : \n', sort_array2d_axis1)

row 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
col 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


**-정렬된 행렬의 인덱스를 반환하기**
- np.argsort() : 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 이용, 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환
- 내림차순으로 정렬시에 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1]과 같이 [::-1] 적용

In [52]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [53]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


- 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 뒤에 소개할 판다스 DataFrame 칼럼과 같은 메타 데이터 가질 수 없음, 따라서 실제 값과 그 값이 뜻하는 메타 데이커를 별도의 ndarray로 각각 가져야만 함

In [54]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 :', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


####선형대수 연산 - 행렬 내적과 전치 행렬 구하기
**-행렬 내적(행렬 곱)**
- 행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산 가능
- 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행개수가 동일해야 내적 연산 가능



In [55]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


**-전치 행렬**
- 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬 - transpose
- np.transpose() 이용

In [56]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
